### ISSUE TITLE
Add git

### ISSUE THREAD

**Issue by hello-smile6** [Darin755/browser-buildroot#1]
Every dev environment needs git. (What about gcc? )

**Comment by Darin755** [comment]
https is currently broken so git does not work most of the time. You can use curl for the time being.

**Comment by hello-smile6** [comment]
> https is currently broken so git does not work most of the time. You can use curl for the time being.

Could you just install git anyway?

**Comment by Darin755** [comment]
Yes I am working on it

**Comment by hello-smile6** [comment]
> Yes I am working on it

Okay. Would the GNOME desktop environment be possible?

**Comment by Darin755** [comment]
no, that would be a horrific experience. If small window manager such as fluxbox runs very slow just imagine how slow gnome shell would be.

**Comment by hello-smile6** [comment]
> no, that would be a horrific experience. If small window manager such as fluxbox runs very slow just imagine how slow gnome shell would be.

Then openbox? It's usable.

**Comment by Darin755** [comment]
I added git. Please open a separate issue for anything unrelated
